version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hamza
      - POSTGRES_USER=hamza
      - POSTGRES_DB=hamza
